apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: segundo-pod
    meuApp: meuapp2
spec: 
  containers:
    - name: container-pod-2
      image: nginx:latest
      ports: 
        - containerPort: 80