apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector: 
    app: segundo-pod
    meuApp: meuapp2
  ports: 
    - port: 9000
     targetPort: 80 # implicitamente é igual ao port se não explicitar