apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec: 
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      #targetPort:80 # implicitamente é igual ao port se não explicitar
  selector:
    app:  primeiro-pod